### PR TITLE
add optional CodiMD exercise

### PR DESCRIPTION
**Pull request by tobyhodges**
This exercise will be really useful when teaching the lesson in a workshop, as a way to gather the relevant information about learners and their repositories. This info will inevitably come in handy for troubleshooting later in the lesson!

### CODE REVIEW

**Comment by sstevens2** [comment]
Working on review but I'm wondering should we use codimd for this workshop?  My colleague setup etherpads when we setup the workshop but could switch it out?

**Review by sstevens2 — APPROVED** [review]
Looks good!

**Comment by tobyhodges** [comment]
> I'm wondering should we use codimd for this workshop?

Anne and I created this one while we were planning the workshop earlier today: https://codimd.carpentries.org/2020-11-11-jekyll-pages?edit

Is it alright for us to switch? I think it would be helpful to back up the Markdown usage we'll teach in the lesson with the note-taking too. Or do you tend to use specific features of the etherpad (e.g. chat) a lot in these mini-workshops?

**Comment by sstevens2** [comment]
That sounds great!  

Could we move the info for the issues/timings/instructor stuff to a separate document? I started filling in my usual etherpad setup [here](https://codimd.carpentries.org/KyHEeesgS7mXKjwwvmHcrw?edit). I could move some of that stuff over and move the For instructors stuff to my link instead?

> > I'm wondering should we use codimd for this workshop?
> 
> Anne and I created this one while we were planning the workshop earlier today: https://codimd.carpentries.org/2020-11-11-jekyll-pages?edit
> 
> Is it alright for us to switch? I think it would be helpful to back up the Markdown usage we'll teach in the lesson with the note-taking too. Or do you tend to use specific features of the etherpad (e.g. chat) a lot in these mini-workshops?

**Comment by tobyhodges** [comment]
Absolutely, sounds good to me. I’ll finish my prep on Monday or Tuesday and
get everything finalised then.

**Comment by sstevens2** [comment]
Ok rearranged, feel free to edit as you see fit. Will post links in slack too and then I'll go ahead and merge this PR

[Learner CodiMD](https://codimd.carpentries.org/2020-11-11-jekyll-pages?edit)
[Instructor/Helper Notes CodiMD](https://codimd.carpentries.org/KyHEeesgS7mXKjwwvmHcrw?edit)

**Pull request merged**
