### PR TITLE
Resolves #279: Tidying up screenshots for new GitHub pages interface

### LINKED ISSUE #279: Update screenshots for new GitHub interface
In #276, @Sparrow0hawk wrote:

>  some of the screenshots are slightly outdated with the new GitHub settings UI.

### PR DESCRIPTION
**Pull request by Sparrow0hawk**
This PR aims to resolve #279 with the following changes:

- new screenshots with updated GitHub pages interface, it is mainly the left hand panel that has changed so overall the steps don't actually look a lot different. I've re-done all the screenshots for the **Enabling GitHub Pages** section for consistency
- Also removed an duplicate item in the ordered list
Please let me know if this is OK/if you'd rather the images in a different format/smaller

### CODE REVIEW

**Review by tobyhodges — CHANGES_REQUESTED** [review]
This is really helpful @Sparrow0hawk, thank you 🙌 

Please could you downsize the images? They will be displayed in the page at 900px width. I like to have the source file slightly larger than that, e.g. for anyone who wants to view the image in a separate tab, but I think 1500px would be plenty.

**Comment by Sparrow0hawk** [comment]
No problem @tobyhodges c387bb2 now includes all image files set to width 1500px.

**Comment by tobyhodges** [comment]
@Sparrow0hawk https://github.com/carpentries-incubator/jekyll-pages-novice/commit/c387bb2e154bd9b65365005ad2207cf622f3dd54 seems to include downsized versions of the current screenshots, rather than your new, improved versions?

**Comment by Sparrow0hawk** [comment]
@tobyhodges apologies! Made some local errors across branches which I accidentally pushed, should now all be fixed with **new** images

**Review by tobyhodges — APPROVED** [review]

**Comment by tobyhodges** [comment]
Looks good now @Sparrow0hawk 👍 thanks again.

**Pull request merged**
