### PR TITLE
resizing screenshots for gh-pages episode

### PR DESCRIPTION
**Pull request by sstevens2**
Think this is the last one for #51. Looks like the later episodes don't have as many screenshots, at least yet.

### CODE REVIEW

**Comment by tobyhodges** [comment]
Thank you @sstevens2. Did you settle on some standard for width/resolution of the screenshots? If so, it would be great to include that information somewhere in the repository for future reference. The README or CONTRIBUTING, perhaps?

**Comment by sstevens2** [comment]
Sorry, I didn't exactly settle on a standard.  I varied the width based on the size of the screenshot, the wider/larger screenshots I set at 600-800width, but the smaller ones I put at 200-400 mostly.

**Review by annefou — APPROVED** [review]
For me it looks fine on my screen. I am not sure we really need a standard for this or if we should agree on a standard it would be for the original images.

**Comment by tobyhodges** [comment]
Yes, at some stage we should define expectations for quality of screenshot images to be included in the lesson. We can do that in CONTRIBUTING.md at a later date.

Merging this now. Thank you @sstevens2

**Pull request merged**
