### PR TITLE
Resizing images for markdown lesson

### PR DESCRIPTION
**Pull request by sstevens2**
Related to #51 

This will conflict with #85

### CODE REVIEW

**Comment by sstevens2** [comment]
Fixed conflicts from merge of #85

**Comment by unode** [comment]
While going though the intro, I noticed I almost missed a paragraph between screenshots.
There's a continuity of white background so it all blends together...

screenshot_2020-11-04_01-38-17_467336879
 
**Can we maybe add an outline to the images, a drop shadow effect or something along these lines?**

**Comment by unode** [comment]
Sorry, mixed tabs with my last comment. Too many on screenshots :sweat_smile:

**Review by annefou — APPROVED** [review]
Yes.I don't see any problems with this PR; it can be merged smoothly! thanks.

**Pull request merged**
