### PR TITLE
WIP: {% include %} Exercises

### LINKED ISSUE #17: Exercise: `include`
in `05-starting-jekyll.md`

need an exercise to test knowledge of `_includes` and `{% include ... %}`

### PR DESCRIPTION
**Pull request by tobyhodges**
Fixes #17 

So far this is only one exercise. It should bridge the gap nicely to talk about page layouts in the next episode. Note I retrospectively adjusted the example source in the GH pages episode to make the content of our example pages consistent.

I'd still like to add one more exercise on includes, perhaps introducing another structural element we can re-use later e.g. a "the current date is: {{site.time}}" element, which we could return to and make more human-readable in the Filters episode. I'd love a more authentic use of `site.time` though, if anyone can suggest one...

### CODE REVIEW

**Review by anenadic — APPROVED** [review]
Looking good, thx for tidying up all those whitespaces @tobyhodges. Approving.

**Comment by tobyhodges** [comment]
> thx for tidying up all those whitespaces @tobyhodges

you can thank my text editor for doing that automatically 😆

**Comment by anenadic** [comment]
Which editor are you using @tobyhodges? Need to look up that option - I am using RubyMine or PyCharm interchangeably.

**Comment by tobyhodges** [comment]
Atom, on which it seems to be a default setting.

**Comment by anenadic** [comment]
Nice, everyone is moving to atom it seems. Need to check it out 👍 .

**Pull request merged**
