### PR TITLE
Added overview diagram to intro and wrap-up episodes

### LINKED ISSUE #216: Introduction episode or soon after: add overview diagram
A diagram of different technologies that grows as we teach different episodes, how different technologies fit together. Also starting from simple diagram and then building a more complex version adding e.g. YAML, Liquid, etc.  throughout would be also very good but is a separate issue - see #218 .

### PR DESCRIPTION
**Pull request by anenadic**
This PR:

- adds an "overview of technologies covered in this lesson" diagram at the start of the lesson and also in the wrap up callout
- mentions HTML and Markdown as desirable but not compulsory knowledge before attending the workshop

Either modifications are up for discussion. Suggestions on the diagram most welcome. Fixes #216 .

### CODE REVIEW

**Comment by tobyhodges** [comment]
I like both these changes, @anenadic. My only comment is that I would like to see the diagram as an SVG, but that is something we can take care of at a later date. Approving but not merging yet, to leave space for others to review/comment.

**Review by tobyhodges — APPROVED** [review]

**Comment by anenadic** [comment]
SVG sounds like a good idea @tobyhodges - I just do not have the right tools for that at the moment but that can be sorted.

**Comment by unode** [comment]
Added SVG version of same diagram.
Only minor differences from original and included also GitLab.
Used a light background instead of black. Looked less contrasting in the rendered website.

**Comment by unode** [comment]
PS: we may want to remove the PNG from the git history if we aren't going to use it to avoid growing the repo.

**Review by unode — APPROVED** [review]

**Comment by tobyhodges** [comment]
Thank you for the SVG, @unode 👍 Maybe slightly picky, but could you replace the font with something _sans serif_, to keep consistent with the rest of the lesson please?

**Comment by unode** [comment]
Was using `Calibri` which should be sans serif but maybe doesn't show well if you don't have this font.
Now updated to use `DejaVu Sans`. Hopefully better.

**Comment by anenadic** [comment]
Thank you @unode - I was just looking into tools to draw SVGs when I saw your diagram. Fabulous!

**Pull request merged**
