### PR TITLE
Implement togglable GitLab content & add GitLab intro

### PR DESCRIPTION
**Pull request by unode**
This pull request adds the HTML/CSS/JS bits to allow
toggling between GitHub and GitLab content.

Currently only the introduction has (some) dual content.
I'll include the GitLab introduction in this pull request.
Will be adding the equivalent steps from GitHub and a GitLab specific section referencing [how to configure GitLab for Jekyll](https://docs.gitlab.com/ee/user/project/pages/getting_started/pages_ci_cd_template.html).

When building locally the GitHub/GitLab selector will allow selecting both simultaneously for easier editing.
In GitHub Pages builds only one will be shown at a time.

On local builds GitHub and GitLab content will have a light blue or light orange background, respectively.
No background will be set on GitHub Pages builds.

### CODE REVIEW

**Comment by unode** [comment]
The Intro isn't complete yet but feedback is welcome on how the content is displayed.

I ended up going for something different from the tabbed sections we discussed.
I found that the [tabs used in the unix lesson e.g. in the setup section](https://swcarpentry.github.io/shell-novice/setup.html) forced either one big tab with alternative content or too many interruptions in the content flow with several smaller tabbed sections, making it visually disruptive.

The current approach makes alternating between Git[La|Hu]b content unnoticeable. I'm currently using a CSS debug feature to visually distinguish the two.

**Comment by unode** [comment]
This is rebased on #247 to avoid some merge conflicts.
Will also need to be rebased on #246 once that PR receives final approval.

Marking this feature beta and providing beta GitLab content for Introduction and alpha for "Authoring Markdown"
Will follow with GitLab Pages intro by which this would be ready for a first merge.

**Comment by unode** [comment]
With the move to the new template system happening from May 2023 I'm not sure if this issue still makes sense.

I guess the crux is if we want to keep GitLab as an alternative in the same lesson or if instead we make it into a separate lesson. Any strong opinions about either?

**Comment by anenadic** [comment]
I am not sure if toggable content will be possible in the new Workbench @unode from May 2023. If people have time, maybe they can look into and contributing this feature to the Workbench (unless it is already there).

**Comment by tobyhodges** [comment]
There is an argument for keeping this lesson in the Jekyll template, so that it can continue to serve as a "living example" of he tooling and skills it aims to teach.

However, there are also myriad reasons to migrate to the Workbench.

Perhaps we should have a maintainers meeting some time soon? It's been a while and there are things to discuss.

**Comment by anenadic** [comment]
> There is an argument for keeping this lesson in the Jekyll template, so that it can continue to serve as a "living example" of he tooling and skills it aims to teach.
> 
> However, there are also myriad reasons to migrate to the Workbench.
> 
> Perhaps we should have a maintainers meeting some time soon? It's been a while and there are things to discuss.

We have our next maintainers meeting scheduled for Monday, February 6, 13:30 – 14:30 GMT (UTC+0). Would be good to meet if people are up for is - we have not had one in ages.

**Comment by unode** [comment]
I'm at the moment available to meet on that time slot and would totally be up for it.

**Comment by unode** [comment]
In light of GitHub actions and GitLab no longer being so centered on Jekyll we decided to abandon this direction.
If enough motivation is gathered we can always revisit.

**Pull request closed without merging**
