### PR TITLE
Resolves #278: Add callout about use & attribution of images online 

### LINKED ISSUE #278: Add callout about use & attribution of images online
In #276, @Sparrow0hawk wrote:

> I spent some time showing how to include images and we talked through using images from an existing URL and if the image was uploaded to the repository, cue some debate about attribution and appropriate use of images from the internet!

A callout should be added to the lesson, with some brief discussion of image use & attribution, to reflect the discussion described here.

### PR DESCRIPTION
**Pull request by Sparrow0hawk**
This PR aims to address #278 by adding a callout to episode 2 highlighting issues around reuse of images and appropriate attribution.

I'm not happy with this current draft and feel perhaps it would be useful to link to either some more discussion around image reuse or links to guide people around responsible use of images online. 

So welcoming any suggestions!

### CODE REVIEW

**Review by sstevens2 — APPROVED** [review]
Thanks for the PR!  This is a nice addition.  Happy to take as is and have one suggestion/discussion point below.

Do you think it might be worth mention public domain images specifically in this callout?

**Comment by Sparrow0hawk** [comment]
Sure! Do you have a suggestion around phrasing?

**Comment by sstevens2** [comment]
Not sure maybe.."Anyone can re-use and edit Public Domain images so searching for images in the public domain."?  With an addition of "It is still good practice to give credit when possible, even for public domain images."?

**Comment by Sparrow0hawk** [comment]
@sstevens2 i've added some lines, using your suggestions, re public domain images. Let us know what you think and if you're happy we can merge this PR

**Review by sstevens2 — APPROVED** [review]

**Comment by sstevens2** [comment]
Thanks @Sparrow0hawk! Merged!

**Pull request merged**
