### PR TITLE
Remove client-side from SVG image

### PR DESCRIPTION
**Pull request by unode**
This fixes issue #105

### CODE REVIEW

**Comment by tobyhodges** [comment]
Looks great @unode! Please could you also adjust the wording of the figure caption, to make clear that the image is a modified version of the one originally published in JS4DS? (line 128 of `_episodes/introduction.md`)

**Comment by unode** [comment]
Done

**Comment by unode** [comment]
Actually, hold this for a bit longer.

**Comment by unode** [comment]
ok, pushed an SVG that has the glitches fixed, at least on my editor.

**Comment by unode** [comment]
...and re-added your correction that got lost with the forced push.

**Comment by unode** [comment]
Good to go now.

**Comment by tobyhodges** [comment]
Thanks @unode!

**Pull request merged**
