### PR TITLE
review introduction

### PR DESCRIPTION
**Pull request by annefou**
Rather than filling an issue with lots of details, I thought it would be faster and more efficient to directly draft my review:
-  fix numbering in exercise.
- Add description in text to allow copy/paste: this option is mostly for self-learners

Please delete this line and the text below before submitting your contribution.

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The Carpentries Team at team@carpentries.org.  

---

### CODE REVIEW

**Comment by unode** [comment]
Looks good to me.

**Comment by tobyhodges** [comment]
Happy for this to be merged as soon as it's ready, @annefou

**Comment by annefou** [comment]
@tobyhodges I actually forgot it was a draft PR! On my side it is also ready to go.

**Comment by tobyhodges** [comment]
Thanks @annefou

**Pull request merged**
